docker-defaults: &docker-defaults
  docker:
    - image: docker:18.03.0-ce-git
  working_directory: ~/app

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose==1.16.1
      - run:
          name: Run tests
          command: docker-compose run test
  push:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build . -t nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
      - run:
          name: Authenticate with dockerhub
          command: docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push branch-tagged image
          command: docker push nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
  push_latest:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build . -t nyulibraries/kubefigs
      - run:
          name: Authenticate with dockerhub
          command: docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push latest image
          command: docker push nyulibraries/kubefigs

workflows:
  version: 2
  build-test-and-push:
    jobs:
      - test
      - push:
          requires:
            - test
      - push_latest:
          requires:
            - push
          filters:
            branches:
              only: master
