docker-defaults: &docker-defaults
  docker:
    - image: docker:18.03.0-ce-git
  working_directory: ~/app

dc-setup: &dc-setup
  run:
    name: Install dependencies
    command: |
      apk add --no-cache python3
      pip3 install docker-compose==1.16.1

test: &test
  run:
    name: Test
    command: docker-compose run test

version: 2
jobs:
  test_and_push:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - <<: *test
      - run:
          name: Build docker image
          command: docker build . -t nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
      - run:
          name: Authenticate with dockerhub
          command: docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push branch-tagged image
          command: docker push nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
  test_and_push_latest:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - <<: *test
      - run:
          name: Build docker image
          command: docker build . -t nyulibraries/kubefigs
      - run:
          name: Authenticate with dockerhub
          command: docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push latest image
          command: docker push nyulibraries/kubefigs

workflows:
  version: 2
  build-test-and-push:
    jobs:
      - test_and_push:
          filters:
            branches:
              ignore: master
      - test_and_push_latest:
          filters:
            branches:
              only: master
