# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose==1.16.1
      - run:
          name: Run tests
          command: |
            docker-compose build
            docker-compose run test
      - run:
          name: Deploy docker image
          command: |
            docker build . -t nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
            docker push nyulibraries/kubefigs:${CIRCLE_BRANCH//\//_}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag nyulibraries/kubefigs:master nyulibraries/kubefigs
              docker push nyulibraries/kubefigs
            fi
